version: '3'
services:
  static:
    restart: always
    build: ./web-ui
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "33061:3306"

  web:
    restart: always
    build: ./web-services
    #we compile here instead of at build because when running we get a persistent volume that we can use for maven's cache
    command: "sh -c 'mvn package && java -jar services/auditing/target/auditing-1.0.jar'"
    ports:
      - "8080:8080"
    volumes:
      - ./web-services:/code
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - FIREBASE_CRED_PATH=/code/firebase-credentials.json
    links:
      - mysql
    depends_on:
      - fiat
      - mysql

  fiat:
    restart: always
    build: ./fiat-engine
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
